version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222
    steps:
      - checkout
      - run: sbt compile
  test:
    docker:
      - image: circleci/openjdk:8u222
    steps:
      - checkout
      - run: sbt test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build